[package]
name = "noclip-support"
version = "0.0.0"
categories = ["wasm"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[features]
default = ["wee_alloc"]

[dependencies]
wasm-bindgen = "0.2.45"
wee_alloc = { version = "0.4.2", optional = true }

[dependencies.web-sys]
version = "0.3.48"
features = ["console"]
